/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eg.edu.alexu.cse.oop.draw;

import java.awt.Color;
import java.awt.Point;
import java.io.File;
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLClassLoader;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Aliaa Abbas
 */
public class UIDesign extends javax.swing.JFrame {

    
    /**
     * Creates new form UIDesign
     */
    public UIDesign() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jColorChooser1 = new javax.swing.JColorChooser();
        jLabel10 = new javax.swing.JLabel();
        jColorChooser2 = new javax.swing.JColorChooser();
        colorShape = new javax.swing.JButton();
        jDialog2 = new javax.swing.JDialog();
        moveLeft = new javax.swing.JButton();
        moveUp = new javax.swing.JButton();
        moveRightBtn = new javax.swing.JButton();
        moveDown = new javax.swing.JButton();
        stopBtn = new javax.swing.JButton();
        jDialog3 = new javax.swing.JDialog();
        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new DrawingCanvas();
        lineBtn = new javax.swing.JButton();
        rectBtn = new javax.swing.JButton();
        squareBtn = new javax.swing.JButton();
        triBtn = new javax.swing.JButton();
        ovalBtn = new javax.swing.JButton();
        circBtn = new javax.swing.JButton();
        undoBtn = new javax.swing.JButton();
        redoBtn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        editBtn = new javax.swing.JButton();
        moveBtn = new javax.swing.JButton();
        copyBtn = new javax.swing.JButton();
        colorBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        loadBtn = new javax.swing.JButton();
        runBtn = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        jDialog1.setLocation(new java.awt.Point(400, 150));
        jDialog1.setMinimumSize(new java.awt.Dimension(550, 500));
        jDialog1.setResizable(false);

        jLabel9.setText("Stroke Color:");

        jLabel10.setText("Fill Color:");

        colorShape.setText("Color");
        colorShape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorShapeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jColorChooser2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(colorShape)
                        .addGap(143, 143, 143))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jColorChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorShape)))
        );

        jDialog2.setLocation(new java.awt.Point(600, 230));
        jDialog2.setMinimumSize(new java.awt.Dimension(185, 185));
        jDialog2.setResizable(false);

        moveLeft.setText("<");
        moveLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveLeftActionPerformed(evt);
            }
        });

        moveUp.setText("^");
        moveUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveUpActionPerformed(evt);
            }
        });

        moveRightBtn.setText(">");
        moveRightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveRightBtnActionPerformed(evt);
            }
        });

        moveDown.setText("v");
        moveDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveDownActionPerformed(evt);
            }
        });

        stopBtn.setText("*");
        stopBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(moveLeft)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moveUp)
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(stopBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(moveDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moveRightBtn)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(moveUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moveLeft)
                    .addComponent(moveRightBtn)
                    .addComponent(stopBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moveDown)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jDialog3.setLocation(new java.awt.Point(400, 250));
        jDialog3.setMinimumSize(new java.awt.Dimension(620, 400));

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog3Layout.createSequentialGroup()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 63, -1, -1));

        lineBtn.setText("Line");
        lineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineBtnActionPerformed(evt);
            }
        });
        getContentPane().add(lineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 33, 80, 24));

        rectBtn.setText("Rectangle");
        rectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectBtnActionPerformed(evt);
            }
        });
        getContentPane().add(rectBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 34, -1, -1));

        squareBtn.setText("Square");
        squareBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareBtnActionPerformed(evt);
            }
        });
        getContentPane().add(squareBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 34, 80, -1));

        triBtn.setText("Triangle");
        triBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triBtnActionPerformed(evt);
            }
        });
        getContentPane().add(triBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 34, 80, -1));

        ovalBtn.setText("Ellipse");
        ovalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ovalBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ovalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 34, 80, -1));

        circBtn.setText("Circle");
        circBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circBtnActionPerformed(evt);
            }
        });
        getContentPane().add(circBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 34, 80, -1));

        undoBtn.setText("Undo");
        undoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoBtnActionPerformed(evt);
            }
        });
        getContentPane().add(undoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 117, 73, -1));

        redoBtn.setText("Redo");
        redoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redoBtnActionPerformed(evt);
            }
        });
        getContentPane().add(redoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 117, 71, -1));

        jComboBox1.setMaximumRowCount(50);
        jComboBox1.setMaximumSize(new java.awt.Dimension(56, 20));
        jComboBox1.setMinimumSize(new java.awt.Dimension(56, 20));
        jComboBox1.setPreferredSize(new java.awt.Dimension(56, 20));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 171, 150, -1));
        jComboBox1.getAccessibleContext().setAccessibleName("<Shapes>");

        jLabel1.setText("Select Shape:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 146, 150, 19));

        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        getContentPane().add(editBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 195, 73, -1));

        moveBtn.setText("Move");
        moveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(moveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 195, 71, -1));

        copyBtn.setText("Copy");
        copyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyBtnActionPerformed(evt);
            }
        });
        getContentPane().add(copyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 224, 73, -1));

        colorBtn.setText("Colorize");
        colorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorBtnActionPerformed(evt);
            }
        });
        getContentPane().add(colorBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 224, -1, -1));

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 253, 71, -1));

        loadBtn.setText("Load");
        loadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 33, 73, -1));

        runBtn.setText("Run");
        runBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runBtnActionPerformed(evt);
            }
        });
        getContentPane().add(runBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 33, 71, -1));

        jComboBox2.setMaximumRowCount(50);
        jComboBox2.setSelectedItem(null);
        jComboBox2.setMaximumSize(new java.awt.Dimension(56, 20));
        jComboBox2.setMinimumSize(new java.awt.Dimension(56, 20));
        jComboBox2.setPreferredSize(new java.awt.Dimension(56, 20));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 88, 150, -1));

        jLabel11.setText("Extra Shapes (load)");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 64, 150, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineBtnActionPerformed
        // TODO add your handling code here:        
        current = new MyLine();
        this.getInput(current);
    }//GEN-LAST:event_lineBtnActionPerformed

    private void rectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectBtnActionPerformed
        // TODO add your handling code here:;
        // Generic Dialog trial
        current = new MyRectangle();
        this.getInput(current);
    }//GEN-LAST:event_rectBtnActionPerformed

    private void squareBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareBtnActionPerformed
        // TODO add your handling code here:
        current = new MySquare();
        this.getInput(current);
    }//GEN-LAST:event_squareBtnActionPerformed

    private void triBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triBtnActionPerformed
        // TODO add your handling code here:
        current = new MyTriangle();
        this.getInput(current);
    }//GEN-LAST:event_triBtnActionPerformed

    private void ovalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ovalBtnActionPerformed
        // TODO add your handling code here:
        current = new MyEllipse();
        this.getInput(current);
    }//GEN-LAST:event_ovalBtnActionPerformed

    private void circBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circBtnActionPerformed
        // TODO add your handling code here:
        current = new MyCircle();
        this.getInput(current);
    }//GEN-LAST:event_circBtnActionPerformed

    private void undoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoBtnActionPerformed
        // TODO add your handling code here:
        DrawingCanvas canvas = (DrawingCanvas)jPanel1;
        if((canvas.deleted.isEmpty())){
            if(canvas.shapes.isEmpty()) return;
            canvas.undo();
            jComboBox1.removeItemAt(--counter);
            
        }
        else {
            current = canvas.deleted.pop(); 
            canvas.shapes.add(current);
            jComboBox1.addItem(current.getClass().getSimpleName()+(++counter));
            
        }
        canvas.repaint();
    }//GEN-LAST:event_undoBtnActionPerformed

    private void redoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redoBtnActionPerformed
        // TODO add your handling code here:
        DrawingCanvas canvas = (DrawingCanvas)jPanel1;
        if(canvas.stack1.isEmpty()) return;
        canvas.redo();
        jComboBox1.addItem(canvas.getShapes()[counter++].getClass().getSimpleName()+counter);
    }//GEN-LAST:event_redoBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        DrawingCanvas canvas = (DrawingCanvas)jPanel1;
        if (jComboBox1.getItemCount()==0) return;
        current = (Shape)canvas.getShapes()[jComboBox1.getSelectedIndex()];
        edit = true;
        this.getInput(current);
    }//GEN-LAST:event_editBtnActionPerformed

    private void moveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveBtnActionPerformed
        // TODO add your handling code here:
        DrawingCanvas canvas = (DrawingCanvas)jPanel1;
        if (jComboBox1.getItemCount()==0) return;
        current = canvas.getShapes()[jComboBox1.getSelectedIndex()];
        jDialog2.setVisible(true);
    }//GEN-LAST:event_moveBtnActionPerformed

    private void copyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyBtnActionPerformed
        // TODO add your handling code here:
        DrawingCanvas canvas = (DrawingCanvas)jPanel1;
        if (jComboBox1.getItemCount()==0) return;
        try {
            current = (Shape)(canvas.getShapes()[jComboBox1.getSelectedIndex()].clone());
            canvas.addShape(current);
        } catch (CloneNotSupportedException ex) {
            Logger.getLogger(UIDesign.class.getName()).log(Level.SEVERE, null, ex);
        }
        jComboBox1.addItem(current.getClass().getSimpleName()+(++counter));
    }//GEN-LAST:event_copyBtnActionPerformed

    private void colorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorBtnActionPerformed
        // TODO add your handling code here:
        DrawingCanvas canvas = (DrawingCanvas)jPanel1;
        if (jComboBox1.getItemCount()==0) return;
        current = canvas.getShapes()[jComboBox1.getSelectedIndex()];
        jDialog1.setVisible(true);
    }//GEN-LAST:event_colorBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        DrawingCanvas canvas = (DrawingCanvas)jPanel1;
        if (jComboBox1.getItemCount()==0) return;
        current = canvas.getShapes()[jComboBox1.getSelectedIndex()];
        canvas.deleted.push(current);
        canvas.removeShape(current);
//        jComboBox1.removeItemAt(jComboBox1.getSelectedIndex());
//        jComboBox1.
//        counter--;
        jComboBox1.removeAllItems();
        counter=0;
        for (Shape sh : canvas.getShapes()){
            jComboBox1.addItem(sh.getClass().getSimpleName()+(++counter));
        }
        canvas.repaint();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void colorShapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorShapeActionPerformed
        // TODO add your handling code here:
        current.setColor(jColorChooser1.getColor());
        current.setFillColor(jColorChooser2.getColor());
        DrawingCanvas canvas = (DrawingCanvas)jPanel1;
        canvas.repaint();
        jDialog1.setVisible(false);
    }//GEN-LAST:event_colorShapeActionPerformed

    private void stopBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopBtnActionPerformed
        // TODO add your handling code here:
        jDialog2.setVisible(false);
    }//GEN-LAST:event_stopBtnActionPerformed

    private void moveRightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveRightBtnActionPerformed
        // TODO add your handling code here:
        DrawingCanvas canvas = (DrawingCanvas)jPanel1;
        current.setPosition(new Point(current.getPosition().x+5, current.getPosition().y));
        canvas.repaint();
    }//GEN-LAST:event_moveRightBtnActionPerformed

    private void moveLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveLeftActionPerformed
        // TODO add your handling code here:
        DrawingCanvas canvas = (DrawingCanvas)jPanel1;
        current.setPosition(new Point(current.getPosition().x-5, current.getPosition().y));
        canvas.repaint();
    }//GEN-LAST:event_moveLeftActionPerformed

    private void moveUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveUpActionPerformed
        // TODO add your handling code here:
        DrawingCanvas canvas = (DrawingCanvas)jPanel1;
        current.setPosition(new Point(current.getPosition().x, current.getPosition().y-5));
        canvas.repaint();
    }//GEN-LAST:event_moveUpActionPerformed

    private void moveDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveDownActionPerformed
        // TODO add your handling code here:
        DrawingCanvas canvas = (DrawingCanvas)jPanel1;
        current.setPosition(new Point(current.getPosition().x, current.getPosition().y+5));
        canvas.repaint();
    }//GEN-LAST:event_moveDownActionPerformed

    private void loadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBtnActionPerformed
        // TODO add your handling code here:
        DrawingCanvas canvas = (DrawingCanvas)jPanel1;
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Jar files", "jar");
        jFileChooser1.setFileFilter(filter);
        jFileChooser1.showOpenDialog(null);
        File f = jFileChooser1.getSelectedFile();
        String name = javax.swing.JOptionPane.showInputDialog("Enter Qualified Name: ");
        
        try{
            URL url = f.toURL();
            URL[] urls = new URL[]{url};
            ClassLoader loader = new URLClassLoader(urls); 
            Class myClass = Class.forName(name, true, loader);
            canvas.installPluginShape(myClass);
            jComboBox2.addItem(myClass.toString());
        }
        catch (MalformedURLException ex){ Logger.getLogger(UIDesign.class.getName()).log(Level.SEVERE, null, ex); }
        catch (ClassNotFoundException ex){ Logger.getLogger(UIDesign.class.getName()).log(Level.SEVERE, null, ex); }
    }//GEN-LAST:event_loadBtnActionPerformed

    private void runBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runBtnActionPerformed
        // TODO add your handling code here:
        DrawingCanvas canvas = (DrawingCanvas)jPanel1;
        if (jComboBox2.getItemCount()==0) return;
//        jComboBox1.addItem(jComboBox2.getSelectedItem().toStreing());
//        System.out.println("working");
        Class plugin = canvas.getSupportedShapes().get(jComboBox2.getSelectedIndex());
        
        try{
//         System.out.println("working");
          Constructor constructor = plugin.getDeclaredConstructor();
          constructor.setAccessible(false);
          current = (Shape)constructor.newInstance();
//            System.out.println("working");
        } catch (NoSuchMethodException ex) {
            Logger.getLogger(UIDesign.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SecurityException ex) {
            Logger.getLogger(UIDesign.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(UIDesign.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(UIDesign.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(UIDesign.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvocationTargetException ex) {
            Logger.getLogger(UIDesign.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.getInput(current);
    }//GEN-LAST:event_runBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UIDesign().setVisible(true);
            }
        });
        
    }
    private void getInput(Shape shape){
        int result;
        DrawingCanvas canvas = (DrawingCanvas)jPanel1;
        JTextField xField = new JTextField(5);
        JTextField yField = new JTextField(5);
        xField.setText(""+shape.getPosition().x);
        yField.setText(""+shape.getPosition().y);
        JPanel myPanel = new JPanel();
        myPanel.add(new JLabel("x:"));
        myPanel.add(xField);
        myPanel.add(Box.createHorizontalStrut(15)); // a spacer 
        myPanel.add(new JLabel("y:"));
        myPanel.add(yField);
        JTextField[] fieldText = new JTextField[10];
        JLabel[] fieldLabel = new JLabel[10];
        int i=0;
        for(String key : shape.getProperties().keySet()){
            fieldLabel[i] = new JLabel(key);
            fieldText[i]= new JTextField(String.valueOf(shape.getProperties().get(key)), 5);
            myPanel.add(fieldLabel[i]);
            myPanel.add(fieldText[i]);
            myPanel.add(Box.createHorizontalStrut(15));
            i++;
        }
        result = JOptionPane.showConfirmDialog(null, myPanel, 
               "Please Enter X and Y Values", JOptionPane.OK_CANCEL_OPTION);
        if(result==JOptionPane.OK_OPTION){
            shape.setPosition(new Point(Integer.parseInt(xField.getText()), Integer.parseInt(yField.getText())));
            i=0;
            for(String key : shape.getProperties().keySet()){
                shape.getProperties().put(key, Double.parseDouble(fieldText[i].getText()));
                i++;
            }
        if(!edit){
           shape.setColor(Color.black);
           shape.setFillColor(Color.white);
           counter++;
           canvas.addShape(shape);
           jComboBox1.addItem(shape.getClass().getSimpleName()+counter);
        }
        }
        edit = false;
        canvas.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton circBtn;
    private javax.swing.JButton colorBtn;
    private javax.swing.JButton colorShape;
    private javax.swing.JButton copyBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lineBtn;
    private javax.swing.JButton loadBtn;
    private javax.swing.JButton moveBtn;
    private javax.swing.JButton moveDown;
    private javax.swing.JButton moveLeft;
    private javax.swing.JButton moveRightBtn;
    private javax.swing.JButton moveUp;
    private javax.swing.JButton ovalBtn;
    private javax.swing.JButton rectBtn;
    private javax.swing.JButton redoBtn;
    private javax.swing.JButton runBtn;
    private javax.swing.JButton squareBtn;
    private javax.swing.JButton stopBtn;
    private javax.swing.JButton triBtn;
    private javax.swing.JButton undoBtn;
    // End of variables declaration//GEN-END:variables
    private Shape current;
    private boolean edit;
    private int counter;
}
